config/routes.rb
Rails.application.routes.draw do
  # Devise routes
  devise_for :devise_users, controllers: {
    sessions: 'devise_user/sessions',
    registrations: 'devise_user/registrations'
  }

  # Static pages
  root 'static_pages#home'

  # Animal routes
  resources :animals

  namespace :api do
    namespace :v1 do
      resources :animals
    end
  end
  
  # Dashboard
  get '/dashboard', to: 'dashboard#index'

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_devise_user!
    
    def index
        @user = current_devise_user
        @animals = Animal.all
    end

    private  
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>
<p>Bem-vindo ao seu dashboard, <%= @user.name %>!</p>
<p>E-mail: <%= @user.email %></p>
<p>Data de Nascimento: <%= @user.date_of_birth %></p>
<p>Celular: <%= @user.phone %></p>
<%= button_to 'Logout', destroy_devise_user_session_path, method: :delete %>
<%= link_to "Cadastrar Animal", new_animal_path %>
<br>
<% if @animals.present? %>
  <% @animals.each do |animal| %>
    <div>
      <h3><%= animal.name %></h3>
      <p>Genêro: <%= animal.gender %></p>
      <p>Raça: <%= animal.breed %></p>
      <p>Idade: <%= animal.age %> anos</p>
      <p>Descrição: <%= animal.additional_info %></p>
      <p><%= link_to "Ver", animal_path(animal) %></p>
      <p><%= link_to "Editar", edit_animal_path(animal) %></p>
      <p><%= button_to 'Remover', animal_path(animal), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
  <% end %>
<% else %>
  <p>O site não possui animais cadastrados ainda.</p>
<% end %>