config/routes.rb
Rails.application.routes.draw do
  # Devise routes
  devise_for :devise_users, controllers: {
    sessions: 'devise_user/sessions',
    registrations: 'devise_user/registrations'
  }

  # Static pages
  root 'static_pages#home'

  # Animal routes
  resources :animals

  namespace :api do
    namespace :v1 do
      resources :animals
    end
  end
  
  # Dashboard
  get '/dashboard', to: 'dashboard#index'

  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_one_attached :photo
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_devise_user!

  def new
    @animal = Animal.new
  end
  
  def show
    @animal = Animal.find(params[:id])
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to dashboard_path, notice: "Pet cadastrado com sucesso."
    else
      render :new, notice: "Não foi possível registrar o pet"
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to dashboard_path, notice: "Animal atualizado com seucesso."
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to dashboard_path, notice: "Animal removido com sucesso."
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :breed, :age, :additional_info, :gender, :photo)
  end

end

app/controllers/api/v1/animals_controller.rb
class Api::V1::AnimalsController < Api::V1::ApiController
    before_action :set_animal, only: [:show, :update, :destroy]
  
    def index
      @animals = Animal.all
      render json: @animals
    end
  
    def show
      render json: @animal
    end
  
    def create
      @animal = Animal.new(animal_params)
      if @animal.save
        render json: @animal, status: :created
      else
        render json: @animal.errors, status: :unprocessable_entity
      end
    end
  
    def update
      if @animal.update(animal_params)
        render json: @animal
      else
        render json: @animal.errors, status: :unprocessable_entity
      end
    end
  
    def destroy
      @animal.destroy
      head :no_content
    end
  
    private
  
    def set_animal
      @animal = Animal.find(params[:id])
    end
  
    def animal_params
      params.require(:animal).permit(:name, :species, :age)
    end
  end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: @animal) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.label :gender %>
    <%= form.select :gender, ['Female', 'Male'] %>
  </div>

  <div>
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :additional_info %>
    <%= form.text_area :additional_info %>
  </div>

  <%= form.submit "Salvar Alterações" %>
<% end %>

app/views/animals/edit.html.erb
<h1>Editar Animal</h1>

<%= form_with(model: @animal, url: animal_path(@animal), method: :patch) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <%= form.label :gender %>
    <%= form.select :gender, ['Female', 'Male'] %>
  </div>

  <div>
    <%= form.label :breed %>
    <%= form.text_field :breed %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :additional_info %>
    <%= form.text_area :additional_info %>
  </div>

  <%= form.submit "Salvar Alterações" %>
<% end %>

app/views/animals/new.html.erb
<h1>Cadastrar Novo Animal</h1>

<%= form_with(model: @animal, url: animals_path, local: true, html: { multipart: true }) do |form| %>
   <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div>
    <%= form.label :gender %>
    <%= form.select :gender, ['Female', 'Male'] %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :additional_info %>
    <%= form.text_area :additional_info %>
  </div>

  <div>
    <%= form.submit "Cadastrar Animal" %>
  </div>
<% end %>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>

<p>
  <% if @animal.photo.attached? %>
    <strong>Photo:</strong>
    <%= image_tag url_for(@animal.photo) %>
  <% end %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @animal.gender %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', dashboard_path %>